# Generated by Django 3.2.14 on 2022-07-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=1000)),
                ('drink', models.BooleanField(default=False)),
            ],
        ),
    ]
