# Generated by Django 3.2.14 on 2022-07-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_uploadimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimages',
            old_name='drink',
            new_name='image',
        ),
    ]
