# Generated by Django 3.2.14 on 2022-07-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_rename_drink_uploadimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimages',
            name='name',
        ),
    ]
